//global
const FETCH_TRACKS = 'FETCH_TRACKS'
const FETCH_ALBUMS = 'FETCH_ALBUMS'
const FETCH_IMAGES = 'FETCH_IMAGES'
const FETCH_FAVORITES = 'FETCH_FAVORITES'

//player
const PLAY_PLAYLIST = 'PLAY_PLAYLIST'
const PLAY_SONG = 'PLAY_SONG'


// theme
const CHANGE_THEME = "CHANGE_THEME"
const STORE_THEME = "STORE_THEME"

export {
  FETCH_TRACKS,
  FETCH_ALBUMS,
  FETCH_IMAGES,
  FETCH_FAVORITES,
  PLAY_PLAYLIST,
  PLAY_SONG,
  CHANGE_THEME,
  STORE_THEME,
};
