//global
const ADD_TRACKS = 'ADD_TRACKS';
const ADD_ALBUMS = 'ADD_ALBUMS';
const ADD_FOLDERS = "ADD_FOLDERS"
const UPDATE_IMAGE = 'UPDATE_IMAGE';
const ADD_FAVORITES = 'ADD_FAVORITES';
const ADD_COVER_ART = 'ADD_COVER_ART';


//player
const PLAY_PLAYLIST = 'PLAY_PLAYLIST';
const PLAY_SONG = 'PLAY_SONG';

// theme
const CHANGE_THEME = 'CHANGE_THEME';
const STORE_THEME = 'STORE_THEME';

export {
  ADD_TRACKS,
  ADD_ALBUMS,
  ADD_FOLDERS,
  UPDATE_IMAGE,
  ADD_FAVORITES,
  ADD_COVER_ART,
  PLAY_PLAYLIST,
  PLAY_SONG,
  CHANGE_THEME,
  STORE_THEME,
};
